name: novel_app
description: 跨平台小说阅读应用

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.5"

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  equatable: ^2.0.7
  dartz: ^0.10.1
  
  # 依赖注入
  get_it: ^7.6.4
  
  # 网络请求
  dio: ^5.3.2
  http_certificate_pinning: ^3.0.1
  connectivity_plus: ^5.0.1
  
  # 路径处理
  path: ^1.8.3
  
  # 本地存储
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI组件
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  
  # 工具类
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.1.0
  
  # 国际化
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  
  # 资源文件
  assets:
    - assets/images/
    - assets/icons/